### ISSUE TITLE
Exception thrown on query params without a value

### ISSUE THREAD

**Issue by nberger** [nberger/ring-logger#17]
Reported by @little-arhat in clojurians a while ago. Example url that would make it to happen: "http://localhost:14587/?name"

**Comment by nberger** [comment]
@little-arhat: I couldn't reproduce the issue, it would be great if you can provide more information (ring-logger version and how are you creating the logger middleware)

**Comment by little-arhat** [comment]
Can't reproduce it using test suite from `ring-logger`, neither! Will try to extract minimal example from my app where I faced this problem.

**Comment by nberger** [comment]
Thanks!

**Comment by nberger** [comment]
@little-arhat I'm closing this because we couldn't reproduce the issue. Feel free to reopen if you find out how to reproduce it! Thanks!
