### ISSUE TITLE
Filter query string

### ISSUE THREAD

**Issue by kendagriff** [nberger/ring-logger#27]
I have a query string like this: `/login?access_token=xxx123`. ring-logger exposes `redact-keys` to filter access_token from the request params, but it's not filtered from the `query-string`. Any suggestions for filtering it? I'd be happy to submit a pull request.

**Comment by kendagriff** [comment]
No quick suggestions here?

**Comment by nberger** [comment]
There is currently no way to disable the `query-string` logging.

The quick suggestion is to implement your custom messages that would skip `query-string` as shown in https://github.com/nberger/ring-logger#custom-messages-and-how-to-disable-coloring.

I see how this can be a concern for many users, so I'd accept a PR adding an option `log-query-string?` that would avoid logging the `query-string` in the default messages methods. Default should be true to be backwards compatible.

**Comment by kendagriff** [comment]
K, thank you. I'll take a stab at something this coming week...

**Comment by kendagriff** [comment]
In the end, I went with your suggestion above to provide a custom multimethod. We needed to hide the query string conditionally. Thank you!
