### ISSUE TITLE
Migration from 0.7 to 1.0

### ISSUE THREAD

**Issue by dAnjou** [nberger/ring-logger#43]
Is there a migration guide somewhere?

I've seen the [changelog](https://github.com/nberger/ring-logger/blob/master/CHANGELOG.md#100) but it only shows version 1.0 code, not how to get there from version 0.7.

**Comment by Kauko** [comment]
Hey, it's been three years since you opened this issue, so I assume you've successfully migrated or have moved on :D I'll close the issue, please open it again if you need help.
