### ISSUE TITLE
No async support in 1.* version

### ISSUE THREAD

**Issue by kirillsalykin** [nberger/ring-logger#46]
Three arity fns (needed for ring async) just dropped (comparing with 0.7).

**Comment by nberger** [comment]
Hi @kirillsalykin, would you be interested in adding this yourself? I can make you a collaborator if that's the case. Unfortunately I'm not having much time to maintain the project right now.

**Comment by kirillsalykin** [comment]
Hi @nberger , I'd be happy to add it myself.

Thanks.

**Comment by Kauko** [comment]
Hi @nberger , I need async support and could try to produce a PR next week. I can either send the PR from my own fork, or you can add me as a collaborator too.

If you made @kirillsalykin a collaborator, he can probably merge the PR too, since we're currently working for the same company. :)
